spring.application.name=frontend-web
spring.thymeleaf.cache=false

server.port=8080

management.endpoints.web.exposure.include=health,info

app.security.user-name=${APP_USER_NAME:user}
app.security.user-password=${APP_USER_PASSWORD:user123}
app.security.admin-name=${APP_ADMIN_NAME:admin}
app.security.admin-password=${APP_ADMIN_PASSWORD:admin123}

app.backend.base-url=${BACKEND_BASE_URL:http://localhost:8081}
app.backend.username=${BACKEND_USERNAME:admin}
app.backend.password=${BACKEND_PASSWORD:admin123}