spring.application.name=frontend-web
spring.thymeleaf.cache=false

server.port=8080

management.endpoints.web.exposure.include=health,info

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=21MB

app.backend.base-url=${BACKEND_BASE_URL:http://localhost:8081}

app.backend.username=${BACKEND_USERNAME:admin}
app.backend.password=${BACKEND_PASSWORD:admin123}